version: '3'
services:
  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest
    container_name: umami-web
    ports:
      - "3005:3000"
    environment:
      DATABASE_URL: postgresql://umami:umami@db:5432/umami
      DATABASE_TYPE: postgresql
      HASH_SALT: YCq7DeJs9rxqB39CgHVUYqjSB6wGZ9
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
    depends_on:
      - db
    restart: always

  db:
    image: postgres:12-alpine
    container_name: umami-db
    environment:
      POSTGRES_DB: umami
      POSTGRES_USER: umami
      POSTGRES_PASSWORD: umami
    volumes:
      - /share/docker-apps/umami/schema.postgresql.sql:/docker-entrypoint-initdb.d/schema.postgresql.sql:ro
      - /share/docker-apps/umami/umami-db-data:/var/lib/postgresql/data
    restart: always
      
networks:
  default:
    name: proxy-network
    external: true
