version: "3.8"

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:release
    entrypoint: ["/bin/sh", "./start-server.sh"]
    env_file: stack.env
    volumes: 
      - /share/photo-library/immich/uploads:/usr/src/app/upload
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:release
    entrypoint: ["/bin/sh", "./start-microservices.sh"]
    env_file: stack.env    
    volumes:
      - /share/photo-library/immich/uploads:/usr/src/app/upload
    depends_on:
      - redis
      - database
      - typesense
    restart: always

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:release
    env_file: stack.env
    volumes:
      - /share/photo-library/immich/uploads:/usr/src/app/upload
      - /share/docker-apps/immich/model-cache:/cache

    restart: always

  immich-web:
    container_name: immich_web
    image: ghcr.io/immich-app/immich-web:release
    entrypoint: ["/bin/sh", "./entrypoint.sh"]
    env_file: stack.env
    restart: always

  typesense:
    container_name: immich_typesense
    image: typesense/typesense:0.24.0
    environment:
      - TYPESENSE_API_KEY=nCEq%MjqG5nCEq%MjqG5
      - TYPESENSE_DATA_DIR=/data
    logging:
      driver: none
    volumes:
      - /share/docker-apps/immich/tsdata:/data
    restart: always

  redis:
    container_name: immich_redis
    image: redis:6.2
    volumes:
     - /share/docker-apps/immich/redis:/data
    restart: always

  database:
    container_name: immich_postgres
    image: postgres:14
    env_file: stack.env
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: immich
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - /share/docker-apps/immich/pgdata:/var/lib/postgresql/data
    restart: always

  immich-proxy:
    container_name: immich_proxy
    image: ghcr.io/immich-app/immich-proxy:release
    environment:
      - IMMICH_SERVER_URL
      - IMMICH_WEB_URL
    ports:
      - 2283:8080
    logging:
      driver: none
    depends_on:
      - immich-server
    restart: always

    