access_control:
  default_policy: deny
  rules:
      domain: umami.crownparkcomputing
      resources: 
      policy: bypass
    #- domain: umami.crownparkcomputing
    #  policy: two_factor
    #- domain: umami.crownparkcomputing
    #  policy: bypass  