---
###############################################################
#                         Users Database                      #
###############################################################

# This file can be used if you do not have an LDAP set up.

users:
  test-user:
    displayname: "Tester"
    password: "$argon2id$v=19$m=65536,t=3,p=4$4oI0bY5UJg2tzvWamPcipA$hVTeFKR2hM1i103Cw2yd+AS1ethwBgCX8FqzpizAcOU"   #hash using docker run --rm authelia/authelia:latest authelia hash-password 'YCq7DeJs9rxqB39'
    email: tester@domain.tld
#    groups:
#      - admins
...
