---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/bookmarks

- Torrent Sites:
    - Backups-Me:
        - abbr: YT
          href: https://back-ups.me/index.php

    - TorrentLeech:
        - abbr: YT
          href: https://www.torrentleech.org/torrents/top/index/added/-1%20day/orderby/completed/order/desc    

- Entertainment:
    - YouTube:
        - abbr: YT
          href: https://youtube.com/
- NAS URL:
    - Main NAS:
        - abbr: NAS
          href: http://192.168.1.209:9090